apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image-bubu-aqua
  namespace: cicd-bubu-aqua
spec:
  params:
    - name: image
      type: string

  workspaces:
    - name: source

  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      workingDir: $(workspaces.source.path)
      args:
        - --dockerfile=$(workspaces.source.path)/Dockerfile
        - --context=$(workspaces.source.path)
        - --destination=$(params.image)
        - --insecure
        - --skip-tls-verify
